fieldLayouts:
  8cae6da6-b5ad-4983-84de-97d70de2e5e6:
    tabs:
      -
        elements:
          -
            heading: 'Page Preview'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 7e73e940-ba83-4c57-a891-e714157ad300
            instructions: ''
            label: 'Preview Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b0ef870-0127-4663-b045-1f00b6f700a5
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Page Header'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a5703536-4f6d-43a4-bf56-03d93e13bd8a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 50
          -
            fieldUid: 626d91be-b8e9-41e6-87c2-0a08f57d9d92
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 14c42466-5857-416c-abd3-a4f95484385d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Page Body'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 38add3df-2b87-4924-a5a7-8248193d55c7
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: genericPage
hasTitleField: true
name: 'Generic Page'
section: 07d38a58-4d79-4d5d-a086-28c6f4453df0
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
