fieldLayouts:
  6f9e98c9-5889-4934-bea2-8b8296281e5b:
    tabs:
      -
        elements:
          -
            heading: 'Page Preview'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 7e73e940-ba83-4c57-a891-e714157ad300
            instructions: ''
            label: 'Preview Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b0ef870-0127-4663-b045-1f00b6f700a5
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            heading: 'Page Heading'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a5703536-4f6d-43a4-bf56-03d93e13bd8a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 626d91be-b8e9-41e6-87c2-0a08f57d9d92
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Page Body'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 38add3df-2b87-4924-a5a7-8248193d55c7
            instructions: ''
            label: 'Page Builder'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Testimonials
            type: craft\fieldlayoutelements\Heading
          -
            style: tip
            tip: 'Testimonials will automatically display here, edit them in the testimonials section.'
            type: craft\fieldlayoutelements\Tip
          -
            heading: Body
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: ae5298d0-8399-442c-a5c6-5d45859b79af
            instructions: ''
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: homepage
hasTitleField: false
name: 'Home Page'
section: bd1353d3-4834-44ad-a613-e8249eb0ab75
sortOrder: 0
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
