fieldLayouts:
  e160d13d-e873-4b3a-b93b-364b488224f3:
    tabs:
      -
        elements:
          -
            heading: 'Page Preview'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 7e73e940-ba83-4c57-a891-e714157ad300
            instructions: ''
            label: 'Primary Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b0ef870-0127-4663-b045-1f00b6f700a5
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Page Heading'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a5703536-4f6d-43a4-bf56-03d93e13bd8a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 50
          -
            fieldUid: 626d91be-b8e9-41e6-87c2-0a08f57d9d92
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 14c42466-5857-416c-abd3-a4f95484385d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Page Body'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 40c6c975-e7c9-443f-8263-fb034ab7d73b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae5298d0-8399-442c-a5c6-5d45859b79af
            instructions: ''
            label: Description
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2c56bda-09c4-4bb4-bab0-d110057592a8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: portfolios
hasTitleField: true
name: Portfolios
section: b7a387cb-3644-45ab-949d-7ac48165faf8
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
