contentColumnType: string
fieldGroup: 7025c78b-3031-405b-9845-6889983aae90
handle: imageGallery
instructions: ''
name: Gallery
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:c1e922d3-77a8-4ee2-901f-30618fe9cc79'
  defaultUploadLocationSubpath: ''
  limit: '25'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Select Portfolio Images'
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:c1e922d3-77a8-4ee2-901f-30618fe9cc79'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
