dateModified: 1612978955
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: $SYSTEM_EMAIL_SENDER_NAME
  replyToEmail: $SYSTEM_EMAIL_REPLY_TO_ADDRESS
  template: ''
  transportSettings:
    encryptionMethod: ssl
    host: $SYSTEM_EMAIL_HOST_NAME
    password: $SYSTEM_EMAIL_PASSWORD
    port: $SYSTEM_EMAIL_PORT
    timeout: '30'
    useAuthentication: '1'
    username: $SYSTEM_EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
plugins:
  bust:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  cache-flag:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  express-forms:
    edition: lite
    enabled: true
    schemaVersion: 1.0.1
    settings:
      duplicatePreventionEnabled: true
      emailNotificationsDirectoryPath: express-forms/_notifications/
      enhancedUI: true
      honeypotBehaviour: simulate_success
      honeypotEnabled: '1'
      honeypotInputName: form_handler
      name: null
      recaptchaEnabled: ''
      recaptchaLoadScript: '1'
      recaptchaSecretKey: null
      recaptchaSiteKey: null
      recaptchaTheme: light
      showErrorLogBanner: true
  hmsupport:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  linkit:
    edition: standard
    enabled: true
    licenseKey: 1M7QC7P7QY84PDLECATF4K3R
    schemaVersion: 1.0.8
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 0AAK0PBFCTL0FQ01ZQHQ4RBM
    schemaVersion: 3.0.9
  sprout-encode-email:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  trimmer:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  vz-address:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
system:
  edition: pro
  live: true
  name: $EN_US_SITE_NAME
  retryDuration: null
  schemaVersion: 3.6.1
  timeZone: America/Chicago
