enableVersioning: false
handle: portfolios
name: Portfolios
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ae98859a-dab4-4af3-b70d-780ede8c6184:
    enabledByDefault: true
    hasUrls: true
    template: _portfolio/_entry
    uriFormat: 'portfolio/{slug}'
type: channel
